open System
open System.IO
open System.Reflection
open System.Text
open System.Text.Json
open System.Text.RegularExpressions

let fail message =
    eprintfn "Binding generation failed: %s" message
    exit 1

let arguments = fsi.CommandLineArgs |> Array.skip 1
if arguments.Length <> 2 then
    fail "usage: dotnet fsi tools/generate-clr-bindings.fsx <manifest.json> <output.fs>"

let manifestPath = Path.GetFullPath arguments.[0]
let outputPath = Path.GetFullPath arguments.[1]
let document = JsonDocument.Parse(File.ReadAllText manifestPath)
let root = document.RootElement

let validateProperties context allowed (element: JsonElement) =
    element.EnumerateObject()
    |> Seq.iter (fun property ->
        if not (Set.contains property.Name allowed) then
            fail (sprintf "unknown property '%s' in %s" property.Name context))

validateProperties
    "manifest"
    (Set.ofList ["$schema"; "manifestId"; "version"; "bindings"])
    root

let manifestId = root.GetProperty("manifestId").GetString()
if String.IsNullOrWhiteSpace manifestId then fail "manifestId is required"
if not (Regex.IsMatch(manifestId, "^[a-z][a-z0-9-]*$")) then
    fail "manifestId must match ^[a-z][a-z0-9-]*$"
if root.GetProperty("version").GetInt32() <> 1 then fail "only manifest version 1 is supported"

let resolveType name =
    let direct = Type.GetType(name, false)
    if direct <> null then direct
    else
        AppDomain.CurrentDomain.GetAssemblies()
        |> Array.tryPick (fun assembly ->
            let candidate = assembly.GetType(name, false)
            if candidate = null then None else Some candidate)
        |> Option.defaultWith (fun () -> fail ("unknown CLR type " + name))

let converter = function
    | "System.String" -> "ClrString", "string"
    | "System.Boolean" -> "ClrBoolean", "bool"
    | "System.Int32" -> "ClrInt32", "int"
    | "System.Double" -> "ClrDouble", "double"
    | name -> fail ("unsupported conversion type " + name)

let sanitize (name: string) =
    let chars =
        name.ToCharArray()
        |> Array.map (fun character -> if Char.IsLetterOrDigit character then character else '_')
    String(chars)

type Binding = {
    kernelName : string
    clrTypeName : string
    memberName : string
    parameters : string list
    returnType : string
    functionName : string
}

let bindings =
    root.GetProperty("bindings").EnumerateArray()
    |> Seq.map (fun element ->
        validateProperties
            "binding"
            (Set.ofList ["kernelName"; "clrType"; "member"; "parameters"; "returns"])
            element
        let kernelName = element.GetProperty("kernelName").GetString()
        let clrTypeName = element.GetProperty("clrType").GetString()
        let memberName = element.GetProperty("member").GetString()
        let returnType = element.GetProperty("returns").GetString()
        if [kernelName; clrTypeName; memberName; returnType] |> List.exists String.IsNullOrWhiteSpace then
            fail "binding names and types must be non-empty"
        if not (Regex.IsMatch(kernelName, "^[A-Za-z][A-Za-z0-9.-]*$")) then
            fail ("invalid kernel binding name " + kernelName)
        let parameters =
            element.GetProperty("parameters").EnumerateArray()
            |> Seq.map (fun value -> value.GetString())
            |> Seq.toList
        let clrType = resolveType clrTypeName
        let parameterTypes =
            parameters
            |> List.map (fun parameter ->
                converter parameter |> ignore
                resolveType parameter)
            |> List.toArray
        let methodInfo =
            clrType.GetMethod(
                memberName,
                BindingFlags.Public ||| BindingFlags.Static,
                null,
                parameterTypes,
                null)
        if methodInfo = null then
            fail (sprintf "no exact public static method %s.%s(%s)" clrTypeName memberName (String.concat ", " parameters))
        if methodInfo.ReturnType.FullName <> returnType then
            fail (sprintf "return type mismatch for %s: expected %s, found %s" kernelName returnType methodInfo.ReturnType.FullName)
        { kernelName = kernelName
          clrTypeName = clrTypeName
          memberName = memberName
          parameters = parameters
          returnType = returnType
          functionName = sanitize kernelName })
    |> Seq.toList

let duplicate =
    bindings
    |> List.groupBy _.kernelName
    |> List.tryFind (fun (_, values) -> List.length values > 1)
match duplicate with
| Some (name, _) -> fail ("duplicate kernel binding " + name)
| None -> ()

let moduleName =
    Char.ToUpperInvariant(manifestId.[0]).ToString() + manifestId.Substring(1) + "Bindings"
let builder = StringBuilder()
let line (value: string) = builder.AppendLine(value) |> ignore

line "// <auto-generated />"
line "namespace IronKernel.Generated"
line ""
line ("module " + moduleName + " =")
line ""
line "    open IronKernel.Ast"
line "    open IronKernel.Errors"
line "    open IronKernel.Eval"
line "    open IronKernel.ClrBindings"
line ""

for binding in bindings do
    line (sprintf "    let private %s env cont args =" binding.functionName)
    line (sprintf "        match requireGenerated \"%s\" env with" manifestId)
    line "        | Choice1Of2 error -> fail error"
    line "        | Choice2Of2 () ->"
    let converters = binding.parameters |> List.map (converter >> fst) |> String.concat "; "
    line (sprintf "            match convertArguments [%s] args with" converters)
    line "            | Choice1Of2 error -> fail error"
    line "            | Choice2Of2 values ->"
    let arguments =
        binding.parameters
        |> List.mapi (fun index parameter ->
            let _, cast = converter parameter
            sprintf "values.[%d] :?> %s" index cast)
        |> String.concat ", "
    let call = sprintf "%s.%s(%s)" binding.clrTypeName binding.memberName arguments
    if binding.returnType = "System.Void" then
        line ("                " + call)
        line "                bounceContinue env cont Inert"
    else
        line ("                let result = " + call)
        line "                returnObject env cont (result :> obj)"
    line ""

line "    let private applicative invoke ="
line "        Applicative"
line "            (PrimitiveOperative"
line "                { identity = None"
line "                  invoke = invoke })"
line ""
line "    let bindings ="
bindings
|> List.iteri (fun index binding ->
    let prefix = if index = 0 then "        [ " else "          "
    line (sprintf "%s\"%s\", applicative %s" prefix binding.kernelName binding.functionName))
line "        ]"

Directory.CreateDirectory(Path.GetDirectoryName outputPath) |> ignore
File.WriteAllText(outputPath, builder.ToString(), UTF8Encoding(false))
printfn "Generated %d bindings in %s" bindings.Length outputPath
